# Generated by Django 2.0.13 on 2019-04-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=40)),
                ('recipient', models.CharField(max_length=40)),
                ('msj', models.TextField()),
                ('img', models.ImageField(upload_to='img_notes')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
